# Generated by Django 3.0.11 on 2022-01-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0003_auto_20220127_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': '名次',
                'db_table': 'grade',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=30, unique=True, verbose_name='用户名')),
                ('name', models.CharField(blank=True, db_column='name', max_length=128, null=True, verbose_name='姓名')),
                ('password', models.CharField(db_column='password', max_length=256, verbose_name='密码')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True, verbose_name='电子邮箱')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], db_column='sex', default='男', max_length=32, null=True, verbose_name='性别')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Grade')),
                ('subjects', models.ManyToManyField(blank=True, null=True, related_name='subjects', to='myApp.StudentSubject')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
    ]
