# Generated by Django 3.0.11 on 2022-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, unique=True, verbose_name='科目名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
                ('img', models.ImageField(db_column='img', default=None, upload_to='StudentSubject', verbose_name='封面')),
                ('total_points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('category', models.CharField(choices=[('w', '文科'), ('l', '理科'), ('t', '通用')], max_length=30)),
            ],
            options={
                'verbose_name': '学生科目',
                'db_table': 'student_subject',
                'ordering': ['id'],
            },
        ),
    ]
