# Generated by Django 3.0.11 on 2022-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20220127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='category',
            field=models.CharField(choices=[('w', '文科'), ('l', '理科'), ('t', '通用')], max_length=30, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='img',
            field=models.ImageField(blank=True, db_column='img', default=None, null=True, upload_to='StudentSubject', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='total_points',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='总分'),
        ),
    ]
